language: go

go:
  - "1.12"

os:
  - linux

go_import_path: github.com/elliotcourant/meles

install: true

env:
  - GO111MODULE=on

script:
  - ./coverage.sh
  - bash <(curl -s https://codecov.io/bash)